# Generated by Django 3.1.2 on 2020-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0034_auto_20170809_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('U', 'Unclassified'), ('R', 'Rejected'), ('A', 'Accepted'), ('D', 'Duplicated')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='dataextractionfield',
            name='field_type',
            field=models.CharField(choices=[('B', 'Boolean Field'), ('S', 'String Field'), ('F', 'Float Field'), ('I', 'Integer Field'), ('D', 'Date Field'), ('O', 'Select One Field'), ('M', 'Select Many Field')], max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('U', 'Unpublished'), ('P', 'Published')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='selectioncriteria',
            name='criteria_type',
            field=models.CharField(choices=[('I', 'Inclusion'), ('E', 'Exclusion')], max_length=1),
        ),
    ]
